# Generated by Django 4.2.11 on 2025-12-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md2docx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
