# Generated by ChatGPT on 2025-12-29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('md2docx', '0002_conversiontask_original_filename_and_more'),
        ('md2docx', '0002_conversiontask_output_format'),
    ]

    operations = [
    ]
